name: 'github_activity_pipeline'
version: '1.0.0'
config-version: 2

profile: 'github_activity_pipeline'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  github_activity_pipeline:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
